"""HTML dashboard report connector."""

from __future__ import annotations

from pathlib import Path
from typing import Any, ClassVar

import pandas as pd

from jakefsd.connectors.base import REGISTRY, ReportConnector
from jakefsd.models.manifest import StageType


class HtmlDashboardReport(ReportConnector):
    """Render a DataFrame as a styled HTML table/dashboard."""

    name = "html_dashboard"
    stage_type = StageType.REPORT
    config_schema: ClassVar[dict[str, Any]] = {
        "type": "object",
        "required": ["path"],
        "properties": {
            "path": {"type": "string", "description": "Output HTML file path"},
            "title": {"type": "string", "default": "JakeFSD Report"},
            "max_rows": {"type": "integer", "default": 1000},
        },
    }

    def run(self, inputs: dict[str, pd.DataFrame]) -> pd.DataFrame:
        if len(inputs) != 1:
            raise ValueError("html_dashboard expects exactly one upstream input")
        df = next(iter(inputs.values()))

        path = Path(self.config["path"])
        path.parent.mkdir(parents=True, exist_ok=True)
        title = self.config.get("title", "JakeFSD Report")
        max_rows = self.config.get("max_rows", 1000)
        preview = df.head(max_rows)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
body {{ font-family: system-ui, -apple-system, sans-serif; margin: 2rem; }}
table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
th, td {{ border: 1px solid #ddd; padding: 0.5rem; text-align: left; }}
th {{ background: #f4f4f4; }}
tr:nth-child(even) {{ background: #fafafa; }}
.footer {{ margin-top: 1rem; color: #666; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
{preview.to_html(index=False, escape=False)}
<div class="footer">Generated by JakeFSD · {len(df)} total rows · showing first {len(preview)}</div>
</body>
</html>"""

        path.write_text(html, encoding="utf-8")
        return pd.DataFrame({"path": [str(path)], "rows": [len(df)]})


REGISTRY.register(HtmlDashboardReport)
